services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_INTERNAL=${DATABASE_URL_INTERNAL}
      - DATABASE_URL_EXTERNAL=${DATABASE_URL_EXTERNAL}
      - APP_ENV=${APP_ENV:-local}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVICE_NAME=${SERVICE_NAME}
      - NODE_ENV=production
    restart: unless-stopped
